# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudbuild_microservice_demo_cloudbuild]

# This configuration file is used to build and deploy the app into a
# GKE cluster using Google Cloud Build.
#
# PREREQUISITES:
# - Cloud Build service account must have role: "Kubernetes Engine Developer"

# USAGE:
# GCP zone and GKE target cluster must be specified as substitutions
# Example invocation:
# `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ZONE=us-central1-b,_CLUSTER=demo-app-staging .`

steps:
#- name: gcr.io/cloud-builders/gsutil
#  id: download-skaffold-cache
#  args:
#    - 'cp'
#    - '-c'
#    - '${_CACHE_URI}'
#    - '/workspace/cache'                   # always write skaffold cache to filename cache in workspace
- name: gcr.io/k8s-skaffold/skaffold
  id: build-and-push-images
  args:
    - skaffold
    - build
    - '--profile=gcb'
    - '--interactive=false'
    - '--default-repo=${_DEFAUILT_REPOSITORY}'
    - '--file-output=/workspace/artifacts.json'
# Create release in Google Cloud Deploy
- id: deploy-release
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "${_DELIVERY_PIPELINE_NAME}",
      "--description", "buildID=${BUILD_ID},commitId=${REVISION_ID}",
      "--region", "${LOCATION}",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"
    ]    
# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  # machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY #https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts?hl=ko#execute_a_build_using_a_config_file
substitutions:
  _DELIVERY_PIPELINE_NAME: online-boutique-pipeline
  _DEFAUILT_REPOSITORY: us-central1-docker.pkg.dev/${PROJECT_ID}/docker-repo
  _CACHE_URI: gs://cache-for-build/
  _CACHE: cache 
# [END cloudbuild_microservice_demo_cloudbuild]