apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: frontend
  namespace: ob
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: metrics
    interval: 30s